#
# Uber, Inc. (c) 2018
#

py_test(
    name = "test_torchscript_packaging",
    srcs = ["test_torchscript_packaging.py"],
    deps = [],
)

py_test(
    name = "test_pytorch_packaging",
    srcs = ["test_pytorch_packaging.py"],
    deps = [],
)

py_test(
    name = "test_pytorch_strings",
    srcs = ["test_pytorch_strings.py"],
    deps = [],
)

py_test(
    name = "test_tensorflow_packaging",
    srcs = ["test_tensorflow_packaging.py"],
    deps = [],
)

py_test(
    name = "test_tensorflow_strings",
    srcs = ["test_tensorflow_strings.py"],
    deps = [],
)

py_test(
    name = "test_config_utils",
    srcs = ["test_config_utils.py"],
    deps = [],
)

py_test(
    name = "test_tensor_validation",
    srcs = ["test_tensor_validation.py"],
    deps = [],
)
