#
# Uber, Inc. (c) 2018
#

py_test(
    name = "test_torchscript_packaging",
    srcs = ["test_torchscript_packaging.py"],
    deps = [],
)

py_test(
    name = "test_pytorch_packaging",
    srcs = ["test_pytorch_packaging.py"],
    deps = [],
)
