/* Copyright (c) 2020 The Neuropod Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uber_neuropod_RuntimeOptions_RuntimeOptionsNative */

#ifndef _Included_com_uber_neuropod_RuntimeOptions_RuntimeOptionsNative
#define _Included_com_uber_neuropod_RuntimeOptions_RuntimeOptionsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uber_neuropod_RuntimeOptions_RuntimeOptionsNative
 * Method:    nativeCreate
 * Signature: (ZZLjava/lang/String;IZZ)J
 */
JNIEXPORT jlong JNICALL Java_com_uber_neuropod_RuntimeOptions_00024RuntimeOptionsNative_nativeCreate(
    JNIEnv *, jclass, jboolean, jboolean, jstring, jint, jboolean, jboolean);

/*
 * Class:     com_uber_neuropod_RuntimeOptions_RuntimeOptionsNative
 * Method:    nativeDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_uber_neuropod_RuntimeOptions_00024RuntimeOptionsNative_nativeDelete(JNIEnv *,
                                                                                                    jobject,
                                                                                                    jlong);

#ifdef __cplusplus
}
#endif
#endif
