/* Copyright (c) 2020 UATC, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uber_neuropod_NeuropodTensor */

#ifndef _Included_com_uber_neuropod_NeuropodTensor
#define _Included_com_uber_neuropod_NeuropodTensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uber_neuropod_NeuropodTensor
 * Method:    nativeDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_uber_neuropod_NeuropodTensor_nativeDoDelete(JNIEnv *, jobject, jlong);

/*
 * Class:     com_uber_neuropod_NeuropodTensor
 * Method:    nativeGetBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_uber_neuropod_NeuropodTensor_nativeGetBuffer(JNIEnv *, jclass, jlong);

/*
 * Class:     com_uber_neuropod_NeuropodTensor
 * Method:    nativeGetDims
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_uber_neuropod_NeuropodTensor_nativeGetDims(JNIEnv *, jclass, jlong);

/*
 * Class:     com_uber_neuropod_NeuropodTensor
 * Method:    nativeGetTensorType
 * Signature: (J)Lcom/uber/neuropod/TensorType;
 */
JNIEXPORT jobject JNICALL Java_com_uber_neuropod_NeuropodTensor_nativeGetTensorType(JNIEnv *, jclass, jlong);

/*
 * Class:     com_uber_neuropod_NeuropodTensor
 * Method:    nativeGetNumberOfElements
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_uber_neuropod_NeuropodTensor_nativeGetNumberOfElements(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
