#
# Uber, Inc. (c) 2019
#

cc_library(
    name = "eigen",
    hdrs = [
        "eigen.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//neuropod/internal",
        "@eigen3_repo//:eigen3",
    ],
)
