# Run on 16.04 for linux builds
dist: xenial
language: minimal
os:
  - linux
  - osx

before_install:
  # Do everything in a virtualenv
  - sudo pip install -U pip
  - sudo pip install virtualenv
  - virtualenv /tmp/neuropod_venv
  - source /tmp/neuropod_venv/bin/activate

install:
  # Install dependencies
  - ./build/install_system_deps.sh
  - ./build/install_python_deps.sh

script:
  # This builds both the C++ and python versions and runs tests
  - ./build/build.sh
