# Run on 16.04 for linux builds
dist: xenial
language: minimal

# Define a build matrix
matrix:
  include:
    - os: linux
    - os: osx
      env: NEUROPODS_TENSORFLOW_VERSION=1.11.0 NEUROPODS_TORCH_VERSION=1.1.0
    - os: osx
      env: NEUROPODS_TENSORFLOW_VERSION=1.12.0 NEUROPODS_TORCH_VERSION=1.1.0
    - os: osx
      env: NEUROPODS_TENSORFLOW_VERSION=1.13.1 NEUROPODS_TORCH_VERSION=1.2.0.dev20190601

script:
  # Travis changes whether the shell is a TTY or not depending on if there are secret env variables set.
  # Travis also does not set these variables for PRs from outside the repo (e.g. from forks) for security
  # reasons (https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions).
  # This leads to different behavior depending on where the PR came from.
  # To get around this, we always run in a non-interactive shell.
  - set -o pipefail
  - ./build/travis_build.sh < /dev/null | cat
