dist: trusty
language: minimal
os:
  - linux
  - osx

services:
  - docker

install:
  # Install dependencies
  - ./build/install_deps.sh

script:
  # This builds both the C++ and python versions and runs tests
  - docker build -f build/neuropods_cmake.dockerfile -t neuropods .

