version: '2.3'
services:
  test-base:
    build:
      context: .
      dockerfile: build/neuropods.dockerfile
      target: neuropod-build
      args:
        BAZEL_ARGS: --config=asan
    privileged: true
