#
# Uber, Inc. (c) 2018
#

cc_library(
    name = "stream",
    hdrs = [
        "stream.hh",
    ],
    deps = [
        "//neuropods:neuropods_hdrs",
    ],
    visibility = [
        "//neuropods:__subpackages__",
    ],
)
