/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_neuropod_NeuropodValue */

#ifndef _Included_org_neuropod_NeuropodValue
#define _Included_org_neuropod_NeuropodValue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_neuropod_NeuropodValue
 * Method:    nativeToList
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_neuropod_NeuropodValue_nativeToList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_neuropod_NeuropodValue
 * Method:    nativeDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_neuropod_NeuropodValue_nativeDelete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
