/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_neuropod_Neuropod */

#ifndef _Included_org_neuropod_Neuropod
#define _Included_org_neuropod_Neuropod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_neuropod_Neuropod
 * Method:    nativeGetInputFeatureKeys
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_neuropod_Neuropod_nativeGetInputFeatureKeys
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_neuropod_Neuropod
 * Method:    nativeGetInputFeatureDataTypes
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_neuropod_Neuropod_nativeGetInputFeatureDataTypes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_neuropod_Neuropod
 * Method:    nativeNew
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_neuropod_Neuropod_nativeNew__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_neuropod_Neuropod
 * Method:    nativeNew
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_neuropod_Neuropod_nativeNew__Ljava_lang_String_2J
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_neuropod_Neuropod
 * Method:    nativeInfer
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_neuropod_Neuropod_nativeInfer
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_neuropod_Neuropod
 * Method:    nativeCreateTensorsFromMemory
 * Signature: (Ljava/util/Map;J)J
 */
JNIEXPORT jlong JNICALL Java_org_neuropod_Neuropod_nativeCreateTensorsFromMemory
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_neuropod_Neuropod
 * Method:    nativeDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_neuropod_Neuropod_nativeDelete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
