#
# Uber, Inc. (c) 2020
#

cc_library(
    name = "serialization",
    hdrs = [
        "ipc_serialization.hh",
    ],
    visibility = [
        "//neuropod:__subpackages__",
    ],
    deps = [
        "//neuropod/backends:neuropod_backend",
        "@boost_repo//:boost",
    ],
)
