load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("//bazel:python.bzl", "python_repository")

http_archive(
    name = "libtorch_repo_linux",
    build_file = "@//deps:BUILD.libtorch",
    sha256 = "71cd435d664799cfe5d1c53ad1fd63b7cfc5b64ca934ee6dc2d76badd399e7f5",
    strip_prefix = "libtorch",
    url = "https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.0.0.zip",
)

http_archive(
    name = "libtorch_repo_darwin",
    build_file = "@//deps:BUILD.libtorch",
    sha256 = "fe6be5edcc77a7853eadff7bed82955200512810b415150ca2c49fbd7c987c6d",
    strip_prefix = "libtorch",
    url = "https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.0.0.zip",
)

http_archive(
    name = "tensorflow_repo_linux",
    build_file = "@//deps:BUILD.tensorflow",
    sha256 = "fd473e2ef72a446421f627aebe90479b92495965c26843034625677a14d8d64f",
    url = "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.12.0.tar.gz",
)

http_archive(
    name = "tensorflow_repo_darwin",
    build_file = "@//deps:BUILD.tensorflow",
    sha256 = "0f77844966cfe8053eaa74f2b6bc5fecfddac070e4be49bd96ad70d5210dd8cc",
    url = "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-darwin-x86_64-1.12.0.tar.gz",
)

http_archive(
    name = "libjsoncpp_repo",
    build_file = "@//deps:BUILD.libjsoncpp",
    sha256 = "d9393d75b94028e02a31970be9a8c583fe8429ea65d7ec92323be960069c35f3",
    strip_prefix = "jsoncpp-0.8.0",
    url = "https://github.com/open-source-parsers/jsoncpp/archive/0.8.0.tar.gz",
)

http_archive(
    name = "python_numpy_repo_linux",
    build_file = "@//deps:BUILD.numpy",
    sha256 = "99699e3e7df919fc6bbdfbdbc2ccef86a955c6d782f1b284e656ae735317c1b1",
    type = "zip",
    url = "https://files.pythonhosted.org/packages/1e/1f/42ec033fe7522ea5e16352b5491cca5d08bd05fd1d19b5be9dd9d2a3a15d/numpy-1.8.2-cp27-cp27m-manylinux1_x86_64.whl",
)

http_archive(
    name = "python_numpy_repo_darwin",
    build_file = "@//deps:BUILD.numpy",
    sha256 = "860afb63f154777e69908b9daef7d10929f8257526aee9553f6548ed962cd5e7",
    type = "zip",
    url = "https://files.pythonhosted.org/packages/6e/00/667a21ff386d4cc6a77bf16d51623dbc9315a50204f6ed01458b10d1fd34/numpy-1.8.2-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl",
)

http_archive(
    name = "boost_repo",
    build_file = "@//deps:BUILD.boost",
    sha256 = "8361ddefbc1c9c2e449ec94cb8e0da6649d076102cde4ea11adfdd2a73e8411e",
    type = "zip",
    url = "https://downloads.sourceforge.net/project/boost/boost/1.54.0/boost_1_54_0.zip",
    strip_prefix = "boost_1_54_0",
)

python_repository(
    name = "python_repo",
    build_file = "@//deps:BUILD.python",
)

http_archive(
    name = "gtest",
    url = "https://github.com/google/googletest/archive/release-1.8.0.zip",
    sha256 = "f3ed3b58511efd272eb074a3a6d6fb79d7c2e6a0e374323d1e6bcbcc1ef141bf",
    build_file = "@//deps:BUILD.gtest",
    strip_prefix = "googletest-release-1.8.0",
)


http_archive(
    name = "eigen3_repo",
    build_file = "@//deps:BUILD.eigen3",
    sha256 = "3b025b3f82f2b95eb66fced90521b798c169b00fb755ee7f48194cf2d6be2faf",
    url = "https://github.com/eigenteam/eigen-git-mirror/archive/3.2.10.zip",
    strip_prefix = "eigen-git-mirror-3.2.10",
)
