load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("//bazel:python.bzl", "python_repository")
load("//bazel:tensorflow.bzl", "tensorflow_repository")
load("//bazel:libtorch.bzl", "libtorch_repository")

# Use an internal LLVM toolchain instead of the system one
http_archive(
    name = "com_grail_bazel_toolchain",
    strip_prefix = "bazel-toolchain-64bb7aa409c384fb9a35f331adb31658f08eb8bb",
    sha256 = "939b5b58b56946fe38deab6e9f65817a557a5d7a93d2b933b4716ff2cf1e0527",
    url = "https://github.com/grailbio/bazel-toolchain/archive/64bb7aa409c384fb9a35f331adb31658f08eb8bb.tar.gz",
    patches = ["@//bazel:toolchain.patch"],
)

load("@com_grail_bazel_toolchain//toolchain:rules.bzl", "llvm_toolchain")

llvm_toolchain(
    name = "llvm_toolchain",
    llvm_version = "6.0.0",
)

libtorch_repository(
    name = "libtorch_repo",
    build_file = "@//deps:BUILD.libtorch",
)

tensorflow_repository(
    name = "tensorflow_repo",
    build_file = "@//deps:BUILD.tensorflow",
)

http_archive(
    name = "libjsoncpp_repo",
    build_file = "@//deps:BUILD.libjsoncpp",
    sha256 = "d9393d75b94028e02a31970be9a8c583fe8429ea65d7ec92323be960069c35f3",
    strip_prefix = "jsoncpp-0.8.0",
    url = "https://github.com/open-source-parsers/jsoncpp/archive/0.8.0.tar.gz",
)

http_archive(
    name = "python_numpy_repo_linux",
    build_file = "@//deps:BUILD.numpy",
    sha256 = "99699e3e7df919fc6bbdfbdbc2ccef86a955c6d782f1b284e656ae735317c1b1",
    type = "zip",
    url = "https://files.pythonhosted.org/packages/1e/1f/42ec033fe7522ea5e16352b5491cca5d08bd05fd1d19b5be9dd9d2a3a15d/numpy-1.8.2-cp27-cp27m-manylinux1_x86_64.whl",
)

http_archive(
    name = "python_numpy_repo_darwin",
    build_file = "@//deps:BUILD.numpy",
    sha256 = "860afb63f154777e69908b9daef7d10929f8257526aee9553f6548ed962cd5e7",
    type = "zip",
    url = "https://files.pythonhosted.org/packages/6e/00/667a21ff386d4cc6a77bf16d51623dbc9315a50204f6ed01458b10d1fd34/numpy-1.8.2-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl",
)

http_archive(
    name = "boost_repo",
    build_file = "@//deps:BUILD.boost",
    sha256 = "8361ddefbc1c9c2e449ec94cb8e0da6649d076102cde4ea11adfdd2a73e8411e",
    type = "zip",
    url = "https://downloads.sourceforge.net/project/boost/boost/1.54.0/boost_1_54_0.zip",
    strip_prefix = "boost_1_54_0",
)

http_archive(
    name = "pybind11_repo",
    build_file = "@//deps:BUILD.pybind11",
    sha256 = "c62073cd8d4f9209ad64092279e757f5fd83327a5b17a72c04fd0fea27d0d593",
    type = "zip",
    url = "https://github.com/pybind/pybind11/archive/v2.2.4.zip",
    strip_prefix = "pybind11-2.2.4",
)

python_repository(
    name = "python_repo",
    build_file = "@//deps:BUILD.python",
)

http_archive(
    name = "gtest",
    url = "https://github.com/google/googletest/archive/release-1.8.0.zip",
    sha256 = "f3ed3b58511efd272eb074a3a6d6fb79d7c2e6a0e374323d1e6bcbcc1ef141bf",
    build_file = "@//deps:BUILD.gtest",
    strip_prefix = "googletest-release-1.8.0",
)


http_archive(
    name = "eigen3_repo",
    build_file = "@//deps:BUILD.eigen3",
    sha256 = "3b025b3f82f2b95eb66fced90521b798c169b00fb755ee7f48194cf2d6be2faf",
    url = "https://github.com/eigenteam/eigen-git-mirror/archive/3.2.10.zip",
    strip_prefix = "eigen-git-mirror-3.2.10",
)

http_archive(
    name = "mklml_repo_darwin",
    build_file = "@//deps:BUILD.mklml",
    sha256 = "2fbb71a0365d42a39ea7906568d69b1db3bfc9914fee75eedb06c5f32bf5fa68",
    url = "https://github.com/intel/mkl-dnn/releases/download/v0.19/mklml_mac_2019.0.5.20190502.tgz",
    strip_prefix = "mklml_mac_2019.0.5.20190502",
)
